### ISSUE TITLE
issue navigating on mobile

### ISSUE THREAD

**Issue by MarnixCroes** [CoinjoinsOrg/coinjoins#54]
clicking on the dropdown doesn't work at all and clicking on `Wallets` takes a few clicks before it works

![image](https://github.com/CoinjoinsOrg/coinjoins/assets/93143998/3dfa2ab2-d662-4650-8f63-e00fc19f2a74)

**Comment by Gustavojfe** [comment]
it works for me on both Chrome and Safari on an iPhone 13, closing for now but if you still have the problem and you can specify on which device and on which browser, I'll reopen and we'll look at it

**Comment by MarnixCroes** [comment]
https://github.com/CoinjoinsOrg/coinjoins/assets/93143998/c08fd26d-f56d-4dcb-8feb-87d12d4ffe72

Can easily repro, Graphene OS vanadium browser
Can also repro on DDG browser and Firefox
